# Generated by Django 4.1.5 on 2023-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='mobil',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='mate',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='contactos',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contactos',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
