# Generated by Django 4.1.5 on 2023-05-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='descrition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='extimate_end',
            new_name='estimated_end',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='name',
            new_name='title',
        ),
    ]
